"""empty message

Revision ID: 092e8cfea7d9
Revises: 71fbe2abad9a
Create Date: 2021-09-08 16:11:53.142637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092e8cfea7d9'
down_revision = '71fbe2abad9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
